#!/usr/bin/env bash
#
# Script name: dmpower
# Description: Logout, shutdown, reboot or lock screen.
# Dependencies: dmenu, systemd, slock
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor

# An array of options to choose.
declare -a options=(
"Logout"
"Lock screen"
"Reboot"
"Poweroff"
"Suspend"
"Quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -p 'Shutdown menu:')

# What to do when/if we choose one of the options.
case $choice in
    'Logout')
        killall awesome || echo "Process was not running."
        killall bspwm || echo "Process was not running."
        killall dwm || echo "Process was not running."
        killall qtile || echo "Process was not running."
        killall spectrwm || echo "Process was not running."
        killall xmonad || echo "Process was not running."
        ;;
    'Lock screen')
        slock
        ;;
    'Reboot')
        systemctl reboot
        ;;
    'Poweroff')
        systemctl poweroff
        ;;
    'Suspend')
        systemctl suspend
        ;;
	'Quit')
		echo "Program terminated." && exit 0
	;;
    # It is a common practice to use the wildcard asterisk symbol (*) as a final
	# pattern to define the default case. This pattern will always match.
	*)
		exit 0
	;;
esac
